export const SELECCIONAR_USUARIO = "SELECCIONAR_USUARIO";
export const SELECCIONAR_NFT = "SELECCIONAR_NFT";
export const CANTIDAD_NFT = "CANTIDAD_NFT";
export const ACTUALIZAR_TOTAL = "ACTUALIZAR_TOTAL";
export const ACTUALIZAR_RED = "ACTUALIZAR_RED";
